-- ScamCheck Forum — admin dashboard, report workflow, and privacy-safe feedback
--
-- Run this ONCE in the Supabase SQL Editor after:
--   1. supabase_forum_schema.sql
--   2. supabase_forum_moderation_migration.sql
--   3. supabase_forum_media_moderation_migration.sql (if image moderation is used)
--
-- This migration is additive. It keeps existing post-report inserts working,
-- adds defaults for every new report field, and does not grant members any
-- new ability to read reports, feedback, or moderation audit data.
--
-- The existing `profiles.role = 'moderator'` role is the administrator role
-- for this first dashboard. Do not put a service-role key in the browser.

-- ---------------------------------------------------------------------------
-- 1. Give every Forum report a review state and a small, auditable outcome.
-- ---------------------------------------------------------------------------

alter table public.post_reports
  add column if not exists moderation_status varchar(20) not null default 'open',
  add column if not exists action_taken varchar(32) not null default 'none',
  add column if not exists moderation_note varchar(500),
  add column if not exists resolved_by uuid references public.profiles(id) on delete set null,
  add column if not exists resolved_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'post_reports_moderation_status_check'
      and conrelid = 'public.post_reports'::regclass
  ) then
    alter table public.post_reports
      add constraint post_reports_moderation_status_check
      check (moderation_status in ('open', 'reviewing', 'resolved', 'dismissed'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'post_reports_action_taken_check'
      and conrelid = 'public.post_reports'::regclass
  ) then
    alter table public.post_reports
      add constraint post_reports_action_taken_check
      check (action_taken in (
        'none', 'reviewed', 'post_hidden', 'post_rejected', 'post_deleted',
        'member_suspended', 'member_restored'
      ));
  end if;
end;
$$;

create index if not exists post_reports_moderation_queue_idx
  on public.post_reports (moderation_status, created_at asc);

create index if not exists post_reports_post_status_idx
  on public.post_reports (post_id, moderation_status);

-- A moderation event is deliberately separate from the report itself: resolving
-- a report can be audited even when the original post later changes or is removed.
create table if not exists public.forum_moderation_events (
  id bigint generated by default as identity primary key,
  report_id bigint references public.post_reports(id) on delete set null,
  post_id bigint references public.posts(id) on delete set null,
  moderator_id uuid references public.profiles(id) on delete set null,
  action_taken varchar(32) not null,
  note varchar(500),
  created_at timestamptz not null default now(),
  constraint forum_moderation_events_action_check check (action_taken in (
    'none', 'reviewed', 'post_hidden', 'post_rejected', 'post_deleted',
    'member_suspended', 'member_restored'
  ))
);

create index if not exists forum_moderation_events_report_created_idx
  on public.forum_moderation_events (report_id, created_at desc);

create index if not exists forum_moderation_events_post_created_idx
  on public.forum_moderation_events (post_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 2. Store only anonymous, fixed-enum product feedback for dashboard metrics.
--    The original message, image, link, phone number, and account number must
--    never be written here.
-- ---------------------------------------------------------------------------

create table if not exists public.analysis_feedback (
  id bigint generated by default as identity primary key,
  source varchar(24) not null default 'web',
  category varchar(20) not null,
  risk varchar(20) not null,
  created_at timestamptz not null default now(),
  constraint analysis_feedback_source_check check (source in ('web', 'extension', 'desktop', 'mobile')),
  constraint analysis_feedback_category_check check (category in ('incorrect', 'unclear', 'quiz')),
  constraint analysis_feedback_risk_check check (risk in ('AN_TOAN', 'NGHI_NGO', 'NGUY_HIEM'))
);

alter table public.analysis_feedback
  add column if not exists source varchar(24) not null default 'web',
  add column if not exists category varchar(20),
  add column if not exists risk varchar(20),
  add column if not exists created_at timestamptz not null default now();

create index if not exists analysis_feedback_created_at_idx
  on public.analysis_feedback (created_at desc);

create index if not exists analysis_feedback_category_risk_idx
  on public.analysis_feedback (category, risk, created_at desc);

-- ---------------------------------------------------------------------------
-- 3. Row-level security: members may still submit a report using the existing
--    insert policy, but only active moderators may read audit data. Feedback is
--    server-write only; a Vercel/server endpoint should use a Supabase service
--    role to insert the already-validated fixed enums.
-- ---------------------------------------------------------------------------

alter table public.post_reports enable row level security;
alter table public.forum_moderation_events enable row level security;
alter table public.analysis_feedback enable row level security;

revoke all on table public.forum_moderation_events from anon;
grant select on table public.forum_moderation_events to authenticated;

drop policy if exists "Moderators can read moderation audit events" on public.forum_moderation_events;
create policy "Moderators can read moderation audit events"
  on public.forum_moderation_events for select to authenticated
  using (public.is_forum_moderator());

-- There are intentionally no client policies on analysis_feedback. The public
-- site continues to submit only through api/feedback.js; that endpoint must not
-- accept message content and should persist with a server-side service key.
revoke all on table public.analysis_feedback from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. Use one RPC to change a report state. It verifies the moderator role,
--    updates the report, and writes an audit record together. There is no direct
--    UPDATE policy on post_reports, so a member cannot forge a moderator action.
-- ---------------------------------------------------------------------------

create or replace function public.set_forum_report_status(
  p_report_id bigint,
  p_moderation_status varchar,
  p_action_taken varchar default 'none',
  p_note varchar default null
)
returns table (
  id bigint,
  post_id bigint,
  moderation_status varchar,
  action_taken varchar,
  resolved_at timestamptz
)
language plpgsql
security definer set search_path = public
as $$
declare
  safe_note varchar(500);
begin
  if not public.is_forum_moderator() then
    raise exception 'Only an active Forum moderator can review reports.';
  end if;

  if p_moderation_status not in ('open', 'reviewing', 'resolved', 'dismissed') then
    raise exception 'Invalid report moderation status.';
  end if;

  if p_action_taken not in (
    'none', 'reviewed', 'post_hidden', 'post_rejected', 'post_deleted',
    'member_suspended', 'member_restored'
  ) then
    raise exception 'Invalid moderation action.';
  end if;

  safe_note := nullif(left(trim(coalesce(p_note, '')), 500), '');

  update public.post_reports as report
     set moderation_status = p_moderation_status,
         action_taken = p_action_taken,
         moderation_note = safe_note,
         resolved_by = case
           when p_moderation_status in ('resolved', 'dismissed') then auth.uid()
           else null
         end,
         resolved_at = case
           when p_moderation_status in ('resolved', 'dismissed') then now()
           else null
         end,
         updated_at = now()
   where report.id = p_report_id;

  if not found then
    raise exception 'Forum report was not found.';
  end if;

  insert into public.forum_moderation_events (
    report_id, post_id, moderator_id, action_taken, note
  )
  select report.id, report.post_id, auth.uid(), p_action_taken, safe_note
  from public.post_reports as report
  where report.id = p_report_id;

  return query
  select report.id, report.post_id, report.moderation_status,
         report.action_taken, report.resolved_at
  from public.post_reports as report
  where report.id = p_report_id;
end;
$$;

grant execute on function public.set_forum_report_status(bigint, varchar, varchar, varchar) to authenticated;
revoke execute on function public.set_forum_report_status(bigint, varchar, varchar, varchar) from public;

-- Existing moderator buttons change post.status directly. This trigger makes
-- those existing Hide/Reject actions close their open reports automatically,
-- so the future dashboard does not retain false "open" items.
create or replace function public.resolve_forum_reports_after_post_moderation()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  resolved_action varchar(32);
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  if new.status = 'hidden' then
    resolved_action := 'post_hidden';
  elsif new.status = 'rejected' then
    resolved_action := 'post_rejected';
  else
    return new;
  end if;

  with resolved_reports as (
    update public.post_reports as report
       set moderation_status = 'resolved',
           action_taken = resolved_action,
           resolved_by = coalesce(auth.uid(), report.resolved_by),
           resolved_at = coalesce(report.resolved_at, now()),
           updated_at = now()
     where report.post_id = new.id
       and report.moderation_status in ('open', 'reviewing')
     returning report.id
  )
  insert into public.forum_moderation_events (
    report_id, post_id, moderator_id, action_taken, note
  )
  select id, new.id, auth.uid(), resolved_action, 'Closed automatically after post moderation.'
  from resolved_reports;

  return new;
end;
$$;

drop trigger if exists on_forum_post_moderation_resolve_reports on public.posts;
create trigger on_forum_post_moderation_resolve_reports
  after update of status on public.posts
  for each row execute procedure public.resolve_forum_reports_after_post_moderation();

-- ---------------------------------------------------------------------------
-- 5. Read models for the moderator dashboard. Both views use the invoker's
--    permissions plus existing RLS, and explicitly return no rows to members.
--    They intentionally omit reporter_id, email, and other identity fields.
-- ---------------------------------------------------------------------------

create or replace view public.forum_admin_report_queue
with (security_invoker = true)
as
select
  report.id as report_id,
  report.post_id,
  report.reason,
  report.moderation_status,
  report.action_taken,
  report.moderation_note,
  report.created_at as reported_at,
  report.updated_at,
  report.resolved_at,
  post.category as post_category,
  post.title as post_title,
  post.body as post_body,
  post.status as post_status,
  count(*) over (partition by report.post_id) as reports_for_post
from public.post_reports as report
join public.posts as post on post.id = report.post_id
where public.is_forum_moderator()
  and report.moderation_status in ('open', 'reviewing');

revoke all on table public.forum_admin_report_queue from anon;
grant select on table public.forum_admin_report_queue to authenticated;

create or replace view public.forum_admin_moderation_events
with (security_invoker = true)
as
select
  event.id,
  event.report_id,
  event.post_id,
  event.action_taken,
  event.note,
  event.created_at
from public.forum_moderation_events as event
where public.is_forum_moderator();

revoke all on table public.forum_admin_moderation_events from anon;
grant select on table public.forum_admin_moderation_events to authenticated;

-- A narrow, moderator-only metrics RPC. It contains no member identities and
-- is safer than exposing raw feedback events to the browser.
create or replace function public.get_forum_admin_dashboard()
returns table (
  pending_posts bigint,
  open_reports bigint,
  reviewing_reports bigint,
  resolved_reports bigint,
  dismissed_reports bigint,
  hidden_posts bigint,
  suspended_members bigint,
  feedback_last_30_days bigint,
  inaccurate_feedback_last_30_days bigint,
  unclear_feedback_last_30_days bigint,
  practice_feedback_last_30_days bigint,
  latest_report_at timestamptz,
  latest_feedback_at timestamptz
)
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_forum_moderator() then
    raise exception 'Only an active Forum moderator can view dashboard metrics.';
  end if;

  return query
  select
    (select count(*)::bigint from public.posts where status = 'pending'),
    (select count(*)::bigint from public.post_reports where moderation_status = 'open'),
    (select count(*)::bigint from public.post_reports where moderation_status = 'reviewing'),
    (select count(*)::bigint from public.post_reports where moderation_status = 'resolved'),
    (select count(*)::bigint from public.post_reports where moderation_status = 'dismissed'),
    (select count(*)::bigint from public.posts where status = 'hidden'),
    (select count(*)::bigint from public.profiles where forum_status = 'suspended'),
    (select count(*)::bigint from public.analysis_feedback where created_at >= now() - interval '30 days'),
    (select count(*)::bigint from public.analysis_feedback where category = 'incorrect' and created_at >= now() - interval '30 days'),
    (select count(*)::bigint from public.analysis_feedback where category = 'unclear' and created_at >= now() - interval '30 days'),
    (select count(*)::bigint from public.analysis_feedback where category = 'quiz' and created_at >= now() - interval '30 days'),
    (select max(created_at) from public.post_reports),
    (select max(created_at) from public.analysis_feedback);
end;
$$;

grant execute on function public.get_forum_admin_dashboard() to authenticated;
revoke execute on function public.get_forum_admin_dashboard() from public;

-- The member directory deliberately goes through an RPC rather than a raw
-- profiles query. A standalone /admin page is a UX boundary; this role check
-- is the actual data boundary. It returns no email, auth metadata, reporter
-- identity, or suspension reason.
create or replace function public.get_forum_admin_members()
returns table (
  id uuid,
  display_name text,
  role text,
  forum_status text,
  created_at timestamptz
)
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_forum_moderator() then
    raise exception 'Only an active Forum moderator can view Forum members.';
  end if;

  return query
  select
    profile.id,
    profile.display_name::text,
    profile.role::text,
    profile.forum_status::text,
    profile.created_at
  from public.profiles as profile
  order by profile.created_at desc
  limit 100;
end;
$$;

grant execute on function public.get_forum_admin_members() to authenticated;
revoke execute on function public.get_forum_admin_members() from public;

-- Make the new views and RPCs visible to Supabase REST immediately.
notify pgrst, 'reload schema';
