-- ScamCheck Forum — Supabase schema
-- Run this whole file once in Supabase SQL Editor. Every public Forum operation
-- is protected by Row Level Security; the browser uses only Supabase's publishable key.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name varchar(30) not null,
  role varchar(20) not null default 'member' check (role in ('member', 'moderator')),
  forum_status varchar(20) not null default 'active' check (forum_status in ('active', 'suspended')),
  suspended_at timestamptz,
  suspension_reason varchar(300),
  created_at timestamptz not null default now()
);

-- These ALTER statements make the schema safe to run on an existing Forum.
alter table public.profiles add column if not exists forum_status varchar(20) not null default 'active';
alter table public.profiles add column if not exists suspended_at timestamptz;
alter table public.profiles add column if not exists suspension_reason varchar(300);
alter table public.profiles drop constraint if exists profiles_forum_status_check;
alter table public.profiles add constraint profiles_forum_status_check check (forum_status in ('active', 'suspended'));

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  category varchar(32) not null check (category in ('safety', 'question', 'scam-alert', 'discussion')),
  title varchar(140) not null check (char_length(title) between 8 and 140),
  body varchar(4000) not null check (char_length(body) between 20 and 4000),
  status varchar(20) not null default 'published' check (status in ('published', 'hidden')),
  created_at timestamptz not null default now()
);

create index if not exists posts_status_created_at_idx on public.posts (status, created_at desc);

create table if not exists public.replies (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body varchar(2000) not null check (char_length(body) between 2 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists replies_post_created_at_idx on public.replies (post_id, created_at asc);

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reason varchar(300) not null,
  created_at timestamptz not null default now(),
  unique (post_id, reporter_id)
);

create or replace function public.handle_new_forum_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(left(trim(new.raw_user_meta_data ->> 'display_name'), 30), ''), 'ScamCheck member')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_forum_profile on auth.users;
create trigger on_auth_user_created_forum_profile
  after insert on auth.users
  for each row execute procedure public.handle_new_forum_user();

create or replace function public.is_forum_moderator()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'moderator' and forum_status = 'active'
  );
$$;

create or replace function public.is_active_forum_member()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and forum_status = 'active'
  );
$$;

-- A moderator can suspend or restore a member's Forum access. This deliberately
-- does not delete the Supabase Auth account: the person can still use the public
-- ScamCheck tools, while their Forum access is stopped and can be restored.
create or replace function public.set_forum_member_status(
  target_user_id uuid,
  new_forum_status varchar,
  moderation_reason varchar default null
)
returns table (id uuid, display_name varchar, forum_status varchar)
language plpgsql
security definer set search_path = public
as $$
declare
  target_role varchar;
begin
  if not public.is_forum_moderator() then
    raise exception 'Only an active Forum moderator can manage members.';
  end if;
  if target_user_id = auth.uid() then
    raise exception 'A moderator cannot change their own Forum access.';
  end if;
  if new_forum_status not in ('active', 'suspended') then
    raise exception 'Invalid Forum access status.';
  end if;

  select role into target_role from public.profiles where profiles.id = target_user_id;
  if target_role is null then
    raise exception 'Forum member was not found.';
  end if;
  if target_role = 'moderator' then
    raise exception 'Moderator accounts cannot be changed here.';
  end if;

  return query
  update public.profiles
     set forum_status = new_forum_status,
         suspended_at = case when new_forum_status = 'suspended' then now() else null end,
         suspension_reason = case when new_forum_status = 'suspended' then nullif(left(trim(coalesce(moderation_reason, '')), 300), '') else null end
   where profiles.id = target_user_id
  returning profiles.id, profiles.display_name, profiles.forum_status;
end;
$$;

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.replies enable row level security;
alter table public.post_reports enable row level security;

drop policy if exists "Forum members can view profiles" on public.profiles;
create policy "Forum members can view profiles"
  on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_active_forum_member());

drop policy if exists "Forum members can read visible posts" on public.posts;
create policy "Forum members can read visible posts"
  on public.posts for select to authenticated
  using (public.is_active_forum_member() and (status = 'published' or public.is_forum_moderator()));

drop policy if exists "Forum members can publish their posts" on public.posts;
create policy "Forum members can publish their posts"
  on public.posts for insert to authenticated
  with check (public.is_active_forum_member() and auth.uid() = author_id and status = 'published');

drop policy if exists "Moderators can hide posts" on public.posts;
create policy "Moderators can hide posts"
  on public.posts for update to authenticated
  using (public.is_forum_moderator())
  with check (public.is_forum_moderator());

drop policy if exists "Moderators can delete posts" on public.posts;
create policy "Moderators can delete posts"
  on public.posts for delete to authenticated
  using (public.is_forum_moderator());

drop policy if exists "Forum members can read replies" on public.replies;
create policy "Forum members can read replies"
  on public.replies for select to authenticated
  using (
    public.is_active_forum_member()
    and
    exists (
      select 1 from public.posts p
      where p.id = post_id and (p.status = 'published' or public.is_forum_moderator())
    )
  );

drop policy if exists "Forum members can publish replies" on public.replies;
create policy "Forum members can publish replies"
  on public.replies for insert to authenticated
  with check (
    public.is_active_forum_member()
    and auth.uid() = author_id
    and exists (select 1 from public.posts p where p.id = post_id and p.status = 'published')
  );

drop policy if exists "Forum members can report posts" on public.post_reports;
create policy "Forum members can report posts"
  on public.post_reports for insert to authenticated
  with check (public.is_active_forum_member() and auth.uid() = reporter_id);

drop policy if exists "Moderators can review reports" on public.post_reports;
create policy "Moderators can review reports"
  on public.post_reports for select to authenticated
  using (public.is_forum_moderator());

grant usage on schema public to anon, authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert on public.replies to authenticated;
grant insert, select on public.post_reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.set_forum_member_status(uuid, varchar, varchar) to authenticated;

-- Optional, after you have registered your own Forum account:
-- update public.profiles set role = 'moderator' where id = 'YOUR_AUTH_USER_UUID';
